---
title: "Class 12: Structured Text Extraction with LLMs"
author: "Amelia Hopkins"
date: "2026-10-05"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Continuing with the Plane Crash Info Example

```{r crashes, results='hold'}
year = 2025

crash_url = paste0('https://www.planecrashinfo.com/', year, '/', year, '.htm')

crash_page <- rvest::read_html(crash_url, encoding = "ISO-8859-1")

# This should now print without the error
crash_page

## {html_document}
## <html>
## [1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
## [2] <body>\n<p align="center"><b><font face="Arial" color="#B0B6FF" size="5"> ...

# How many <table> elements are on the page?
crash_tables <- crash_page |>
  rvest::html_elements("table") |>
  rvest::html_table()

# From a cleaning perspective:
# [1] Obviously, translate this into a DF instead of a list
# [2] To replace the current headers with row 1 and then delete row
# [3] Convert Date into a date column instead of chr
# [4] More complex cleaning to split multiple information within a cell into separate columns (outside the scope of today's class -- feel free to try AI or regular expressions if you are in 414)

# Back to our pepper shaker analogy
crash_df = crash_tables[[1]] # subsetting a list

colnames(crash_df) = crash_df[1, ]
crash_df = crash_df[-1, ]

# Convert date columns into a date type object
crash_df = crash_df |>
  dplyr::mutate(Date = lubridate::dmy(Date))

dplyr::glimpse(crash_df)
```


## Practice: Salvage Run

```{r game}
page = rvest::read_html("https://isa401-salvage.vercel.app/registry?start=1")
classes = page |>
  rvest::html_elements(".Dreadnought") |>
  rvest::html_text2()
length(classes)   # check this first: one per card

base = "https://isa401-salvage.vercel.app"
starts = seq(from = 1, to = 351 , by = 50)
pages = vector("list", length(starts)) # Initializing the list [similar to initializing the df]
for (i in seq_along(starts)) {
  pg = rvest::read_html(paste0(base, "/registry?start=", starts[i]))
  pages[[i]] = data.frame(
    class = pg |> rvest::html_elements("div > ul > li:nth-child(1) > span") |>
      rvest::html_text2(),
    value = pg |> rvest::html_elements("div > ul > li:nth-child(3) > span") |>
      rvest::html_text2() |> readr::parse_number()
  )
  Sys.sleep(1)   # robots.txt asks for it
}
registry = dplyr::bind_rows(pages)   # 400 rows?

dreadnought_df = registry |>
  dplyr::filter(class == "Dreadnought")

sum(dreadnought_df$value)

```


## ISA 125 Extraction

```{r isa125}
chat = ellmer::chat_openai(
  model = "gpt-5.6-luna"
)

isa125_courseblock = rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/") |>
  rvest::html_elements("#sc_sccoursedescs > div:nth-child(1)") |> # Inspect what you are interested in. Then right click the element to copy the SELECTOR then paste it into your function
  rvest::html_text2()

chat$chat_structured(
  isa125_courseblock,
  type = ellmer::type_object(
    # code is the name of the first element in the returned sublist
    # type_sstring -> forces that element to be of type chr
    code = ellmer::type_string(
      description = "The three letter abbreviation for the course and its number.For example, ISA 999 or FIN 444"
    ),
    name = ellmer::type_string(
      description = "The title of the course without the three letter abbreviation and the number. For example, Introduction to Macroeconomics. Do not return a period after the name"
    ),
    cr_hr = ellmer::type_integer(
      description = "The number of credits shown in parenthesis after the course code and title"
    )
  )
)

```


## All 50 ISA Courses

```{r all_isa_courses}
course_vec = rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/") |>
  rvest::html_elements(".courseblock") |>
  rvest::html_text2()

course_list = as.list(course_vec) # Make it a list

# Copied the schema from the prior example
# We did it for one class and now we apply it to all 50
type_course = ellmer::type_object(
    # code is the name of the first element in the returned sublist
    # type_sstring -> forces that element to be of type chr
    code = ellmer::type_string(
      description = "The three letter abbreviation for the course and its number.For example, ISA 999 or FIN 444"
    ),
    name = ellmer::type_string(
      description = "The title of the course without the three letter abbreviation and the number. For example, Introduction to Macroeconomics. Do not return a period after the name"
    ),
    cr_hr = ellmer::type_integer(
      description = "The number of credits shown in parenthesis after the course code and title"
    )
  )

isa_df = ellmer::parallel_chat_structured(
  chat = chat,
  prompts = course_list,
  type = type_course,
  include_tokens = T,
  include_cost = T
)

sum(isa_df$cost)
```

